name: Unit Test
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.23
        uses: actions/setup-go@v1
        with:
          go-version: 1.23
      - name: Run tests
        run: go test -timeout=30s -count=1 -coverprofile=coverage.txt -v ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  test-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.23
        uses: actions/setup-go@v1
        with:
          go-version: 1.23
      - name: Run tests
        run: go test -timeout=30s -count=1 -coverprofile=coverage.txt -v ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}